name: Build and Release

on:
  push:
    branches:
      - main  # 或者您使用的其他分支

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version number
        id: update_version
        run: |
          # 获取当前版本号
          version=$(node -p "require('./package.json').version")
          # 自动递增版本号
          IFS='.' read -r -a version_parts <<< "$version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV
          # 更新 package.json 中的版本号
          npm version $new_version --no-git-tag-version
          git add package.json
          git commit -m "chore: update version to $new_version"
          git push

      - name: Package files
        run: |
          # 打包所有文件到一个压缩包中
          zip -r release-${{ env.VERSION }}.zip .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Release notes for v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: release-${{ env.VERSION }}.zip